### ISSUE TITLE
How to add else

### ISSUE THREAD

**Issue by zarniak** [zarniak/exercism.io#1]
How to add else to this block with printing "False" if statement is not true
https://github.com/zarniak/exercism.io/blob/df6689bc55c4bf5f9c247f99eb647854ff19ce12/leap.py#L7-L12
@virtuallight

**Comment by virtuallight** [comment]
For if/ekse syntac have a look https://docs.python.org/2/tutorial/controlflow.html#if-statements (that points to Python 2.7 docs but if/else syntax has not changed in Python 3).

In this particular case that would be:
```
def is_leap_year( year ):
   if year%4 == 0 and year%100 != 0:
       print True
  else:
       print False
```

**Comment by zarniak** [comment]
i have error becasue of not exact numer of spaces in indentation :)
