### ISSUE TITLE
test automatically

### ISSUE THREAD

**Issue by zarniak** [zarniak/exercism.io#13]
@virtuallight i have always 2 files - one with solution and one with answer - how can i run the test without rewriting the values to solution file in https://www.onlinegdb.com/online_python_compiler

**Comment by virtuallight** [comment]
@zarniak I'm not sure what you mean. Let me still give it a shot though! So if you are writing your code in https://www.onlinegdb.com/online_python_compiler then have 2 files open there (CTRL+M to add a file):
- `main.py` where you paste the test code from https://raw.githubusercontent.com/zarniak/exercism.io/master/bob/bob_test.py
- `bob.py` where you implement the solution

See https://onlinegdb.com/HJ19X1V5X. When you hit "Run" (F9) then the tests will execute and will show you the output in the console below.

Did that help?

**Comment by zarniak** [comment]
@virtuallight yes, this is what i was looking for - thanks!
