### ISSUE TITLE
move to folder

### ISSUE THREAD

**Issue by zarniak** [zarniak/exercism.io#14]
@virtuallight i want to move reverse-string.py to folder reverse-string - how can i do that?

**Comment by virtuallight** [comment]
@zarniak How are you adding new commits? Through GitHub, IDE, command line...?

**Comment by zarniak** [comment]
@virtuallight through web github.com

**Comment by zarniak** [comment]
@virtuallight you know how to handle this?

**Comment by virtuallight** [comment]
@zarniak https://blog.github.com/2013-03-15-moving-and-renaming-files-on-github/ should help 👀
